---

- name: Create bitcoind group
  group:
    name: "{{ bitcoin_group }}"
    state: present
    system: true

- name: Create bitcoind user
  user:
    name: "{{ bitcoin_user }}"
    group: "{{ bitcoin_group }}"
    home: "{{ bitcoin_home_dir }}"
    comment: "Bitcoin Daemon"
    shell: "/bin/false"
    createhome: true

- name: Ensure bitcoin directories exists
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ bitcoin_user }}"
    group: "{{ bitcoin_group }}"
    mode: '0710'
  with_items:
    - "{{ _bitcoin_data_dir }}"
    - "{{ _bitcoin_conf_dir }}"

- name: Download bitcoin and verify SHA256 checksum
  become: true
  become_user: "{{ bitcoin_user }}"
  get_url:
    url: https://bitcoin.org/bin/bitcoin-core-{{ bitcoin_version }}/bitcoin-{{ bitcoin_version }}-x86_64-linux-gnu.tar.gz
    dest: "{{ bitcoin_home_dir }}/bitcoin-{{ bitcoin_version }}-x86_64-linux-gnu.tar.gz"
    checksum: sha256:https://bitcoin.org/bin/bitcoin-core-{{ bitcoin_version }}/SHA256SUMS.asc

- name: Install bitcoin
  unarchive:
    src: "{{ bitcoin_home_dir }}/bitcoin-{{ bitcoin_version }}-x86_64-linux-gnu.tar.gz"
    dest: /usr/local
    remote_src: true
    extra_opts: [--strip-components=1]
